Writable:
  LogLevel: "INFO"
  StoreAndForward:
    Enabled: false
  Pipeline:
    PerTopicPipelines:
      export-data:
        Id: export-data-pipeline
        Topics: "edgex/events/device/+/+/+/edge-sensor-export-data"
        ExecutionOrder: "TransformJson, HTTPExportData"
      request-pending-commands:
        Id: request-pending-commands-pipeline
        Topics: "edgex/events/device/+/+/+/request-pending-commands"
        ExecutionOrder: "TransformJson, HTTPExportCommandRequest"
    Functions:
      TransformJson:
        Parameters:
          Type: json
      HTTPExportData:
        Parameters:
          Method: post
          MimeType: application/json
          Url: "http://my.api1.net/edgexdata"
      HTTPExportCommandRequest:
        Parameters:
          Method: post
          MimeType: application/json
          Url: "http://my.api3.net/edgexdata"

Service:
  Host: "localhost"
  Port: 59700
  StartupMsg: "app-sample has Started"

MessageBus:
  Disabled: false # Set to true if not using edgex-messagebus Trigger below and don't want Metrics
  Optional:
    ClientId: "app-sample"

Trigger:
  PublishTopic: "sample"
